# Generated by Django 4.2.1 on 2023-05-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_alter_companyaccount_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
