# Generated by Django 4.2.1 on 2023-05-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('medical_typ', models.CharField(max_length=100)),
                ('buy_price', models.CharField(max_length=100)),
                ('sell_price', models.CharField(max_length=100)),
                ('c_gst', models.CharField(max_length=100)),
                ('s_gst', models.CharField(max_length=100)),
                ('batch_no', models.CharField(max_length=100)),
                ('shelf_no', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
                ('mfg_date', models.DateField()),
                ('description', models.TextField()),
                ('in_stock_total', models.IntegerField()),
                ('qty_in_strip', models.IntegerField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_name', models.CharField(max_length=100)),
                ('salt_qty', models.CharField(max_length=100)),
                ('salt_qty_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_app.medicine')),
            ],
        ),
    ]
